<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>Exception &#8211; Learning Site For Ruby</title>
	<atom:link href="http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/index.php/my/category/my-exception/feed/" rel="self" type="application/rss+xml" />
	<link>http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com</link>
	<description></description>
	<lastBuildDate>Wed, 08 Jun 2022 08:21:30 +0000</lastBuildDate>
	<language>my-MM</language>
	<sy:updatePeriod>
	hourly	</sy:updatePeriod>
	<sy:updateFrequency>
	1	</sy:updateFrequency>
	
	<item>
		<title>Rescue Modifier</title>
		<link>http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/index.php/my/2021/05/19/my-rescue-modifier/</link>
				<pubDate>Wed, 19 May 2021 02:42:58 +0000</pubDate>
		<dc:creator><![CDATA[]]></dc:creator>
				<category><![CDATA[Exception]]></category>
		<category><![CDATA[Rubyရဲ့‌ အခြေခံအချက်‌တွေ]]></category>

		<guid isPermaLink="false">http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/?p=1794</guid>
				<description><![CDATA[rescue ကို modifier အနေနဲ့သုံးလို့ရပါတယ်။ exception တက်တဲ့အခါမှာ  return value က rescue ထဲကနေပြန်လာတဲ့ value ပဲဖြစ်မှာပါ အပေါ်က&#160;code&#160;ထဲက&#160;rescue&#160;modifier&#160;အပိုင်းကို&#160;အောက်ပါအတိုင်းအတိုချုံ့ရေးလို့ရပါတယ်. code&#160;ရဲ့&#160;process&#160;ကအတူတူပါပဲချုံ့ရေးလို့ရတယ်လို့ဆိုလိုတာပါ.ဒါပေမဲ့&#160;ဒီလိုချုံ့ရေးထားတဲ့အချိန်မှာတော့&#160;ကိုယ်သတ်မှတ်ချင်တဲ့&#160;exception&#160;class&#160;တွေကိုသတ်မှတ်လို့မရတာတော့ရှိပါတယ်.ဒီလိုမျိုးရေးရင်&#160;StandErrorနဲ့&#160;သူ့&#160;subclass&#160;တွေရဲ့&#160;exception&#160;ကိုတက်ပေးမှာပါ.တကယ်လို့&#160;ကိုယ်က&#160;exception&#160;class&#160;တွေနဲ့&#160;အသေးစိတ်ရေးချင်တယ်ဆိုရင်တော့&#160;begin～end&#160;ကိုသုံးပြီးရေးရမှာပါ.]]></description>
									</item>
		<item>
		<title>Exception ရဲ့ Return Value</title>
		<link>http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/index.php/my/2021/05/19/my-exception-return-value/</link>
				<pubDate>Wed, 19 May 2021 02:42:46 +0000</pubDate>
		<dc:creator><![CDATA[]]></dc:creator>
				<category><![CDATA[Exception]]></category>
		<category><![CDATA[Rubyရဲ့‌ အခြေခံအချက်‌တွေ]]></category>

		<guid isPermaLink="false">http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/?p=1790</guid>
				<description><![CDATA[Ruby ရဲ့ exception မှာ return value ရှိပါတယ်.return ပြန်တဲ့အ‌ခြေအနေက exception တက်တဲ့အချိန်နဲ့ exception မတက်တဲ့အချိန်ဆိုပြီး  ၂ မျိုး ၂ စားကွဲပါတယ်.exception မတက်တဲ့အချိန်ဆိုရင် begin အောက်က နောက်ဆုံး process ကို return ပြန်ပါတယ်.exception တက်တဲ့အချိန်ဆိုရင် rescue အောက်က နောက်ဆုံး process ကို return ပြန်ပါတယ်.]]></description>
									</item>
		<item>
		<title>Exception ရဲ့ Else</title>
		<link>http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/index.php/my/2021/05/19/my-exception-else/</link>
				<pubDate>Wed, 19 May 2021 02:42:38 +0000</pubDate>
		<dc:creator><![CDATA[]]></dc:creator>
				<category><![CDATA[Exception]]></category>
		<category><![CDATA[Rubyရဲ့‌ အခြေခံအချက်‌တွေ]]></category>

		<guid isPermaLink="false">http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/?p=1786</guid>
				<description><![CDATA[Ruby ရဲ့ exception မှာ တစ်ခုရှိတာက exception မတက်တဲ့အချိန်မှာလုပ်ချင်တဲ့အလုပ်မျိုးကိုလုပ်ချင်တယ်ဆိုရင်else ကိုသုံးပြီးရေးလို့ရပါတယ်. အဲ့လိုရေးလို့ရတယ်ဆိုပေမယ့်လဲ&#160;တကယ့်တကယ့်သိပ်ရေးလေ့မရှိကြပါဘူး.exception&#160;မတက်ရင်က&#160;begin&#160;～&#160;rescue&#160;ကိုပဲ&#160;run&#160;တာဖြစ်လို့အဲ့ထဲမှာပဲ&#160;ရေးကြတာများပါတယ် အထက်ပါ&#160;code&#160;နဲ့&#160;output&#160;က&#160;အတူတူပဲဖြစ်မှာပါ]]></description>
									</item>
		<item>
		<title>Retry and Ensure</title>
		<link>http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/index.php/my/2021/05/19/my-retry-ensure/</link>
				<pubDate>Wed, 19 May 2021 02:42:29 +0000</pubDate>
		<dc:creator><![CDATA[]]></dc:creator>
				<category><![CDATA[Exception]]></category>
		<category><![CDATA[Rubyရဲ့‌ အခြေခံအချက်‌တွေ]]></category>

		<guid isPermaLink="false">http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/?p=1724</guid>
				<description><![CDATA[တကယ်လို့ error တစ်ခုခုတက်ခဲ့ပြီး အဲ့ error ကို ထပ်ထပ်ပြီး ပြင်စေချင်တယ်ဆိုရင် rescue ထဲမှာ retry ကိုခံရေးလို့ရပါတယ်.retry ခံရေးထားလိုက်ရင် rescue ရဲ့ begin ကနေ အလုပ်ကို ပြန်စလုပ်ပေးမှာပါ.ဥပမာ network error တွေဘာတွေကြောင့် error တက်ခဲ့မယ်ဆိုရင် ထပ်ထပ်ပြီး retry လုပ်ချင်တယ်ဆိုတဲ့အခါမျိုးမှာသုံးလို့ရပါတယ်. အဲ့ဒီမှာ&#160;တစ်ခုသတိထားရမှာက&#160;process&#160;ကို&#160;ပြန်ပြန်&#160;run&#160;ပေးတဲ့အတွက်&#160;infinite&#160;loop&#160;ဖြစ်နိုင်တဲ့အလားအလာရှိပါတယ်.အဲ့လိုမဖြစ်အောင်ကတော့&#160;count&#160;တွေ&#160;ဘာတွေနဲ့&#160;စစ်ပေးလိုက်လို့ရပါတယ်. exception&#160;တက်သည်ဖြစ်စေ&#160;မတက်သည်ဖြစ်စေ&#160;code&#160;ကို&#160;run&#160;စေချင်တယ်ဆိုရင်တော့&#160;ensure&#160;ကိုသုံးနိုင်ပါတယ်.ensure&#160;အောက်မှာထည့်ထားတဲ့&#160;code&#160;ဟာ&#160;run&#160;ကို&#160;run&#160;သွားမယ့်&#160;code&#160;ဖြစ်ပါတယ်.&#160;&#160;&#160; ဥပမာ&#160;file&#160;ကို&#160;ဖွင့်တဲ့&#160;process&#160;မျိုးဆိုရင်&#160;နောက်ဆုံးမှာ&#160;exception&#160;တက်တက်မတက်တက်file&#160;ကို&#160;ပိတ်ပေးဖို့လိုအပ်ပါတယ်အဲ့လိုမျိုးဆိုရင်&#160;ensure&#160;ကိုသုံးပြီး&#160;အောက်ပါအတိုင်းရေးနိုင်ပါတယ် ensure&#160;အစား&#160;block&#160;ကိုသုံးရင်လဲရပါတယ်. block&#160;ကိုသုံးပြီး&#160;file&#160;ကိုဖွင့်ရင်&#160;method&#160;ပြီးသွားတဲ့အချိန်မှာ&#160;file&#160;ကို&#160;auto&#160;ပိတ်ပေးမှာပါ.]]></description>
									</item>
		<item>
		<title>Exception Class and Inheritance Relationship</title>
		<link>http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/index.php/my/2021/05/19/my-exception-class-inheritance-relationship/</link>
				<pubDate>Wed, 19 May 2021 02:42:21 +0000</pubDate>
		<dc:creator><![CDATA[]]></dc:creator>
				<category><![CDATA[Exception]]></category>
		<category><![CDATA[Rubyရဲ့‌ အခြေခံအချက်‌တွေ]]></category>

		<guid isPermaLink="false">http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/?p=1719</guid>
				<description><![CDATA[rescue ထဲမှာက exception class ကိုကိုင်တွယ်ရမှာမို့ exception class ရဲ့ inheritance relationship တွေအကြောင်းကို သိထားဖို့လိုပါမယ်.ZeroDivisionError တို့ NoMethodError တို့လိုမျိုး exception class တွေအကုန်လုံးဟာ Exception Class ကြီးကို inheritance ယူထားတာပါ.Exception Class ကြီးရဲ့အောက်မှာမှ subclass လေးတွေအနေနဲ့ ထပ်ရှိနေကြတာပါ.Exception Class ကြီးရဲ့ subclass အနေနဲ့အောက်ပါ class တွေရှိကြပါတယ်ဆိုပါစို့.NoMemoryError, SystemExit&#8230;, StandardErrorအဲ့ဒီမှာ တစ်ခုသိထားရမှာက StandardError class အကြောင်းပါပဲ.error တက်နိုင်ခြေအများဆုံး exception တွေကို StandardError class ကနေလုပ်ပေးထားတာပါ.StandardError class အောက်မှာဆိုရင် RuntimeError, NameError, TypeError, ArgumentError,စသည်ဖြင့် error တက်နိုင်ခြေများတဲ့classများရှိကြပါတယ်.တကယ်လို့ rescue မှာ ဘာ class ကိုမှ သတ်မှတ်မပေးခဲ့ဘူးဆိုရင် StandardError class နဲ့ သူ့ရဲ့ subclass တွေရဲ့ exception တွေကိုပဲ run ‌ပေးမှာပါ.StandardError နဲ့ တစ်တန်းတည်းရှိတဲ့ NoMemoryError, SystemExit စတဲ့ Systemနဲ့ပတ်သက်တဲ့ exception တွေကို ဖမ်းပေးမှာမဟုတ်ပါဘူး. အောက်ပါအတိုင်း&#160;Exception&#160;class&#160;ကို‌&#160;ရေးပေးထားလိုက်ရင်တော့&#160;exception&#160;class&#160;နဲ့&#160;subclass&#160;တွေအကုန်လုံး(NoMemoryError,&#160;SystemExit&#160;အပါအဝင်,&#160;StandardError)ကို&#160;ဖမ်းပေးမှာပါ. ဒါပေမဲ့လို့&#160;တကယ့်တကယ်&#160;code&#160;ရေးတဲ့အခါမှာ&#160;တိတိကျကျရေးဖို့လိုအပ်တာကြောင့်&#160;rescue&#160;မှာ&#160;Exception&#160;လို့ရေးလိုက်တာမျိုး..StandardError&#160;လို့ရေးလိုက်တာမျိုး&#160;မလုပ်သင့်ပါ.သူတို့ရဲ့&#160;subclass&#160;တွေအထိ&#160;တိတိကျကျရေးပေးသင့်ပါတယ်. subClass&#160;တွေအထိ&#160;တိတိကျကျရေးတဲ့နေရာမှာလည်း&#160;ဒီတစ်ချက်ကို&#160;သတိထားသင့်ပါတယ်.code&#160;ကို&#160;ကြည့်ပါ. အထက်ပါ&#160;code&#160;ကိုကြည့်ရင်&#160;NameError,&#160;NoMethodError&#160;တွေနဲ့&#160;Exception&#160;ဖမ်းထားတာကို&#160;တွေ့ရမှာပါ.တက်တဲ့&#160;error&#160;ကလည်း&#160;NoMethodError&#160;တက်တာပါ.ဒါပေမဲ့&#160;NameError&#160;ကိုပဲ&#160;exception&#160;ဖမ်းသွားပါတယ်..ဘာကြောင့်ပါလဲ..&#160;အဖြေက&#160;ဒီလိုပါ..အောက်ပါ&#160;class&#160;relationship&#160;တွေကို&#160;ကြည့်ပါ Exception&#160;&#62;&#160;StandardError&#160;&#62;&#160;NameError&#160;&#62;&#160;NoMethodError NameError&#160;က&#160;NoMethodError&#160;ရဲ့&#160;super&#160;class&#160;ဖြစ်နေတဲ့အတွက်&#160;ပထမဆုံးဖမ်းထားတဲ့&#160;NameError&#160;exception&#160;ထဲဝင်သွားတာပါ.အဲ့လိုမျိုးမဖြစ်အောင်&#160;ဘယ်လိုဖြေရှင်းရမလဲဆိုတာကတော့&#160;လွယ်ပါတယ်.subclass&#160;ဖြစ်တဲ့&#160;NoMethodError&#160;exception&#160;ကို&#160;အရင်ဖမ်းထားလိုက်ပါပြီးမှ&#160;သူ့ရဲ့&#160;super&#160;class&#160;တွေကို&#160;exception&#160;ဖမ်းပါ. NoMethodErrorတက်တာကတော့&#160;မှန်သွားပါပြီNameErrorတက်တာကကော&#160;မှန်လား&#160;ကြည့်ကြည့်ပါမယ်.အောက်ပါအတိုင်း&#160;NameError&#160;လည်း&#160;မှန်မှန်ကန်ကန်&#160;exception&#160;ဖမ်းပေးပါတယ်.]]></description>
									</item>
		<item>
		<title>Creating Execption</title>
		<link>http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/index.php/my/2021/05/19/my-create-execption/</link>
				<pubDate>Wed, 19 May 2021 02:41:01 +0000</pubDate>
		<dc:creator><![CDATA[]]></dc:creator>
				<category><![CDATA[Exception]]></category>
		<category><![CDATA[Rubyရဲ့‌ အခြေခံအချက်‌တွေ]]></category>

		<guid isPermaLink="false">http://ec2-52-199-252-147.ap-northeast-1.compute.amazonaws.com/?p=1694</guid>
				<description><![CDATA[Execption တစ်ခုကိုအောက်ပါအတိုင်း create လုပ်နိုင်ပါတယ်. e ဆိုတာက exception object ကိုထည့်ထားတဲ့ variable တစ်ခုပါ..error သာ တက်ခဲ့မယ်ဆိုရင် အဲ့ e variable ထဲကနေ data တွေကို ထုတ်ယူပြီးကြည့်နိုင်ပါတယ်.တစ်ချို့တွေကျတော့ e အစား ex ဆိုတဲ့နာမည်ကိုလည်းပေးတတ်ကြပါတယ်.e.class ဆိုပြီး class ကိုခေါ်ကြည့်ရင် ဘယ် class ရဲ့ exception မှာ error တက်တာလဲဆိုတာကိုသိရမှာဖြစ်ပါတယ်.message method ကိုခေါ်ကြည့်ရင် error message ကို သိရမှာဖြစ်ပြီးတော့backtrace method ကို ခေါ်ကြည့်ရင် ခေါ်ခဲ့တဲ့ method history တွေကို သိရမှာဖြစ်ပါတယ်. ကိုယ်တွေမှာ&#160;error&#160;တက်နိုင်မယ့်&#160;code&#160;တစ်ခုရှိတယ်ဆိုကြပါစို့&#160;..&#160;ဥပမာ အထက်ပါ&#160;code&#160;ကို&#160;run&#160;လိုက်ရင်&#160;အောက်ပါအတိုင်း&#160;ZeroDivisionError&#160;တက်ပါလိမ့်မယ်. အဲ့သလို&#160;error&#160;တက်လာခဲ့ရင်&#160;ဘာလုပ်မလဲဆိုတာမျိုးကို&#160;rescue&#160;အောက်မှာရေးကြရမှာပါ.]]></description>
									</item>
	</channel>
</rss>
